default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: vagrant
  port: 5432

development:
  <<: *default
  database: hpi_swt2_dev

test:
  <<: *default
  database: hpi_swt2_test

production:
  <<: *default
  database: hpi_swt2_production